### ISSUE TITLE
Error: Without memberof Overlay

### ISSUE THREAD

**Issue by yolopunk** [balemy/ldap-commander#148]
### What steps will reproduce the problem?

I'm using the default configuration，as follows

* `docker-compose.yml`
```yaml
version: '3.9'
services:
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - BITNAMI_DEBUG=true
      - LDAP_CONFIG_ADMIN_ENABLED=yes
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=secret
      - LDAP_EXTRA_SCHEMAS=cosine,inetorgperson,nis,bitnami-openldap-memberof
    volumes:
      - 'openldap_data:/bitnami/openldap'
      - './ldap-example-data.ldif:/ldifs/example.ldif'
      - './ldap-memberof.ldif:/opt/bitnami/openldap/etc/schema/bitnami-openldap-memberof.ldif'
  ldap-commander:
    image: balemy/ldap-commander:latest
    container_name: ldap-commander
    ports:
      - "8080:8080"
    depends_on:
      - openldap
    volumes:
      - './config.php:/app/config/ldap.php'
volumes:
  openldap_data:
    driver: local
```

* `config.php`
```php
<?php

return [
    'app' => [
        'loginMessage' => '<b>Demo</b> - Leave username empty, password is "secret".  Demo will be reset every hour.<br>'
    ],
    'ldap-sessions' => [
        [
            'LDAP' => [
                'dsn' => 'ldap://openldap:1389',
                'baseDn' => 'dc=example,dc=org',
                'adminDn' => 'cn=admin,dc=example,dc=org',
![Screen Shot 2024-02-21 at 20 10 47](https://github.com/balemy/ldap-commander/assets/7477825/7d9749c5-eab4-49e6-a400-ff0dfb870fa9)

                'adminPassword' => 'secret',
                'configDn' => 'cn=admin,cn=config',
                'configPassword' => 'configpassword'
            ],
            'UserManager' => [
                'enabled' => true,
            ],
        ],
    ]
];
```
Return error message after login `Could not resolve if of name: olcmemberofgroupoc`

![Screen Shot 2024-02-21 at 20 10 47](https://github.com/balemy/ldap-commander/assets/7477825/4ee1a3ed-5b15-455f-824f-dde1eb58e7d1)

### Additional info

| Q                | A
| ---------------- | ---
| PHP version      |  8.2.14
| LDAP Commander | 0.9.3
| Docker  | 25.0.3
